"""
Administrator routes.
Thesis reference: Chapter III – Use Case Diagram (Fig 3.6), System Flow (Fig 3.4).
Admin functions: staff management, QR generation, attendance review,
payroll computation/approval, payslip generation, reports.
"""

import json
from datetime import datetime, date, timedelta
from flask import (Blueprint, render_template, request, redirect,
                   url_for, flash, session, send_file, jsonify, make_response)
import io

from app.models import get_db
from app.utils.auth import admin_required, hash_password, hash_pin, generate_qr_token
from app.utils.payroll import compute_payroll, save_payroll
from app.utils.pdf_payslip import generate_payslip_pdf
from app.utils.qr_generator import generate_qr_data_url

admin_bp = Blueprint('admin', __name__, url_prefix='/admin')


# ─────────────────────────────────────────────
#  Dashboard
# ─────────────────────────────────────────────
@admin_bp.route('/dashboard')
@admin_required
def dashboard():
    with get_db() as conn:
        stats = {
            'total_staff': conn.execute(
                "SELECT COUNT(*) FROM staff WHERE employment_status='active'").fetchone()[0],
            'today_present': conn.execute(
                "SELECT COUNT(DISTINCT staff_id) FROM attendance "
                "WHERE scan_date=? AND scan_type='time_in'", (date.today().isoformat(),)).fetchone()[0],
            'pending_payroll': conn.execute(
                "SELECT COUNT(*) FROM payroll WHERE status='draft'").fetchone()[0],
            'payslips_issued': conn.execute(
                "SELECT COUNT(*) FROM payslip WHERE is_released=1").fetchone()[0],
        }
        # Recent attendance
        recent_attendance = conn.execute("""
            SELECT a.*, s.first_name || ' ' || s.last_name AS staff_name, s.position
            FROM attendance a
            JOIN staff s ON s.id = a.staff_id
            ORDER BY a.created_at DESC LIMIT 10
        """).fetchall()
        # Pending payrolls
        pending_payrolls = conn.execute("""
            SELECT p.*, s.first_name || ' ' || s.last_name AS staff_name
            FROM payroll p JOIN staff s ON s.id = p.staff_id
            WHERE p.status = 'draft' ORDER BY p.created_at DESC LIMIT 5
        """).fetchall()

    return render_template('admin/dashboard.html',
                           stats=stats,
                           recent_attendance=[dict(r) for r in recent_attendance],
                           pending_payrolls=[dict(r) for r in pending_payrolls])


# ─────────────────────────────────────────────
#  Staff Management
# ─────────────────────────────────────────────
@admin_bp.route('/staff')
@admin_required
def staff_list():
    with get_db() as conn:
        staff = conn.execute("""
            SELECT * FROM staff ORDER BY last_name, first_name
        """).fetchall()
    return render_template('admin/staff_list.html',
                           staff=[dict(r) for r in staff])


def _generate_staff_no(conn) -> str:
    """
    Auto-generate the next sequential Staff No. in the form GB-XXXX
    (4-digit, zero-padded), based on the highest existing numeric
    suffix among staff_no values matching that pattern. Falls back to
    GB-0001 if no staff exist yet.
    """
    rows = conn.execute("SELECT staff_no FROM staff WHERE staff_no LIKE 'GB-%'").fetchall()
    max_n = 0
    for r in rows:
        suffix = r['staff_no'][3:]
        if suffix.isdigit():
            max_n = max(max_n, int(suffix))
    return f"GB-{max_n + 1:04d}"


@admin_bp.route('/staff/add', methods=['GET', 'POST'])
@admin_required
def staff_add():
    with get_db() as conn:
        suggested_staff_no = _generate_staff_no(conn)

    if request.method == 'POST':
        f = request.form
        # Staff No. is auto-generated by default but can still be
        # manually overridden right on the creation form if needed.
        staff_no     = f.get('staff_no', '').strip() or suggested_staff_no
        pin          = f.get('pin', '').strip()
        first_name   = f.get('first_name', '').strip()
        last_name    = f.get('last_name', '').strip()
        email        = f.get('email', '').strip()
        phone        = f.get('phone', '').strip()
        position     = f.get('position', '').strip()
        emp_type     = f.get('employment_type', 'full_time')
        date_hired   = f.get('date_hired', '') or None
        daily_rate   = float(f.get('daily_rate', 0) or 0)
        monthly_rate = float(f.get('monthly_rate', 0) or 0)
        # Deduction amounts are NOT collected on creation — they default
        # from the schema (SSS 1540 / PhilHealth 500 / Pag-IBIG 400
        # monthly totals) and can be overridden later on Staff Details.

        if not all([staff_no, pin, first_name, last_name, position]):
            flash('Required fields: Staff No., PIN, first name, last name, position.', 'danger')
            return render_template('admin/staff_form.html', staff=None, form=f,
                                   suggested_staff_no=suggested_staff_no)
        if not pin.isdigit() or not (4 <= len(pin) <= 8):
            flash('Attendance PIN must be 4–8 digits.', 'danger')
            return render_template('admin/staff_form.html', staff=None, form=f,
                                   suggested_staff_no=suggested_staff_no)

        pin_hash = hash_pin(pin)
        qr_token = generate_qr_token()
        try:
            with get_db() as conn:
                conn.execute("""
                    INSERT INTO staff (staff_no, first_name, last_name, email, phone,
                        position, employment_type, date_hired,
                        daily_rate, monthly_rate, attendance_pin_hash,
                        qr_token, qr_issued_at)
                    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)
                """, (staff_no, first_name, last_name, email, phone,
                      position, emp_type, date_hired,
                      daily_rate, monthly_rate,
                      pin_hash, qr_token))
            flash(f"Staff member {first_name} {last_name} created successfully (Staff No. {staff_no}). "
                  "Print their QR badge from the Staff list.", 'success')
            return redirect(url_for('admin.staff_list'))
        except Exception as e:
            if 'UNIQUE' in str(e):
                flash(f"Staff No. '{staff_no}' is already taken.", 'danger')
            else:
                flash(f"Error creating staff: {e}", 'danger')
            return render_template('admin/staff_form.html', staff=None, form=f,
                                   suggested_staff_no=suggested_staff_no)

    return render_template('admin/staff_form.html', staff=None, form={},
                           suggested_staff_no=suggested_staff_no)


@admin_bp.route('/staff/<int:staff_id>/edit', methods=['GET', 'POST'])
@admin_required
def staff_edit(staff_id):
    with get_db() as conn:
        staff = conn.execute("SELECT * FROM staff WHERE id = ?", (staff_id,)).fetchone()
    if not staff:
        flash('Staff not found.', 'danger')
        return redirect(url_for('admin.staff_list'))
    staff = dict(staff)

    if request.method == 'POST':
        f = request.form
        new_pin = f.get('new_pin', '').strip()
        if new_pin and (not new_pin.isdigit() or not (4 <= len(new_pin) <= 8)):
            flash('Attendance PIN must be 4–8 digits.', 'danger')
            return render_template('admin/staff_form.html', staff=staff, form=staff)
        try:
            with get_db() as conn:
                conn.execute("""
                    UPDATE staff SET staff_no=?, first_name=?, last_name=?, email=?, phone=?,
                        position=?, employment_type=?, date_hired=?,
                        daily_rate=?, monthly_rate=?, sss_monthly_total=?, philhealth_monthly_total=?,
                        pagibig_monthly_total=?, employment_status=?,
                        updated_at=CURRENT_TIMESTAMP
                    WHERE id=?
                """, (f.get('staff_no','').strip(),
                      f.get('first_name','').strip(), f.get('last_name','').strip(),
                      f.get('email','').strip(), f.get('phone','').strip(),
                      f.get('position','').strip(),
                      f.get('employment_type','full_time'),
                      f.get('date_hired','') or None,
                      float(f.get('daily_rate', 0) or 0),
                      float(f.get('monthly_rate', 0) or 0),
                      float(f.get('sss_monthly_total', 1540) or 1540),
                      float(f.get('philhealth_monthly_total', 500) or 500),
                      float(f.get('pagibig_monthly_total', 400) or 400),
                      f.get('employment_status', 'active'),
                      staff_id))
                # Optionally reset the attendance PIN
                if new_pin:
                    conn.execute("UPDATE staff SET attendance_pin_hash=? WHERE id=?",
                                 (hash_pin(new_pin), staff_id))
            flash('Staff record updated.', 'success')
            return redirect(url_for('admin.staff_list'))
        except Exception as e:
            if 'UNIQUE' in str(e):
                flash(f"Staff No. '{f.get('staff_no','')}' is already taken.", 'danger')
            else:
                flash(f"Update failed: {e}", 'danger')

    return render_template('admin/staff_form.html', staff=staff, form=staff)


# ─────────────────────────────────────────────
#  QR Code Management
# ─────────────────────────────────────────────
@admin_bp.route('/staff/<int:staff_id>/qr', methods=['GET', 'POST'])
@admin_required
def staff_qr(staff_id):
    """View / print / regenerate / revoke a staff member's QR badge.

    The QR token is permanent — it does not expire on a timer. The admin
    only changes it when a badge is lost, compromised, or the staff
    member needs to be deactivated from scanning in.
    """
    with get_db() as conn:
        staff = conn.execute("SELECT * FROM staff WHERE id = ?", (staff_id,)).fetchone()
    if not staff:
        flash('Staff not found.', 'danger')
        return redirect(url_for('admin.staff_list'))
    staff = dict(staff)

    if request.method == 'POST':
        action = request.form.get('action', 'regenerate')
        with get_db() as conn:
            if action == 'revoke':
                conn.execute("UPDATE staff SET qr_revoked=1 WHERE id=?", (staff_id,))
                conn.execute(
                    "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
                    ('qr_revoked', json.dumps({'staff_id': staff_id}), session['user_id'])
                )
                staff['qr_revoked'] = 1
                flash('QR badge revoked. The staff member can no longer scan in until '
                      'a new badge is issued.', 'warning')
            else:
                token = generate_qr_token()
                conn.execute("""
                    UPDATE staff SET qr_token=?, qr_issued_at=CURRENT_TIMESTAMP, qr_revoked=0
                    WHERE id=?
                """, (token, staff_id))
                conn.execute(
                    "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
                    ('qr_generated',
                     json.dumps({'staff_id': staff_id, 'token_prefix': token[:8]}),
                     session['user_id'])
                )
                staff['qr_token'] = token
                staff['qr_revoked'] = 0
                flash('New QR badge generated. Reprint and reissue it to the staff member — '
                      'the previous badge will no longer work.', 'success')

    qr_data_url = None
    if staff.get('qr_token') and not staff.get('qr_revoked'):
        qr_data_url = generate_qr_data_url(staff['qr_token'])

    return render_template('admin/staff_qr.html', staff=staff, qr_data_url=qr_data_url)


# ─────────────────────────────────────────────
#  Attendance Management
# ─────────────────────────────────────────────
@admin_bp.route('/attendance')
@admin_required
def attendance_list():
    filter_date  = request.args.get('date', date.today().isoformat())
    filter_staff = request.args.get('staff_id', '')
    with get_db() as conn:
        query = """
            SELECT a.*, s.first_name || ' ' || s.last_name AS staff_name, s.position
            FROM attendance a JOIN staff s ON s.id = a.staff_id
            WHERE a.scan_date = ?
        """
        params = [filter_date]
        if filter_staff:
            query += " AND a.staff_id = ?"
            params.append(filter_staff)
        query += " ORDER BY a.time_in DESC"
        records = conn.execute(query, params).fetchall()
        all_staff = conn.execute(
            "SELECT id, first_name || ' ' || last_name AS name FROM staff "
            "WHERE employment_status='active' ORDER BY last_name").fetchall()

    return render_template('admin/attendance_list.html',
                           records=[dict(r) for r in records],
                           all_staff=[dict(r) for r in all_staff],
                           filter_date=filter_date,
                           filter_staff=filter_staff)


@admin_bp.route('/attendance/manual', methods=['GET', 'POST'])
@admin_required
def attendance_manual():
    """
    Manual attendance entry — for use when the tablet scan kiosk is
    unavailable (system error, power outage, lost/damaged badge, etc.).
    Lets the admin record a time-in and/or time-out directly, bypassing
    the QR + PIN flow entirely. Every manual entry is written to the
    audit log so it's clear afterward which records were added this way
    versus scanned normally.
    """
    with get_db() as conn:
        all_staff = conn.execute("""
            SELECT id, staff_no, first_name || ' ' || last_name AS name
            FROM staff WHERE employment_status='active' ORDER BY last_name
        """).fetchall()

    if request.method == 'POST':
        f = request.form
        staff_id   = f.get('staff_id', '')
        scan_date  = f.get('scan_date', '') or date.today().isoformat()
        time_in    = f.get('time_in', '').strip()
        time_out   = f.get('time_out', '').strip()
        notes      = f.get('notes', '').strip()

        if not staff_id:
            flash('Please select a staff member.', 'danger')
            return render_template('admin/attendance_manual.html',
                                   all_staff=[dict(r) for r in all_staff])
        if not time_in and not time_out:
            flash('Enter at least a time-in or a time-out.', 'danger')
            return render_template('admin/attendance_manual.html',
                                   all_staff=[dict(r) for r in all_staff])

        with get_db() as conn:
            staff = conn.execute("SELECT * FROM staff WHERE id=?", (staff_id,)).fetchone()
            if not staff:
                flash('Staff member not found.', 'danger')
                return render_template('admin/attendance_manual.html',
                                       all_staff=[dict(r) for r in all_staff])

            hours = 0.0
            time_in_full = f"{scan_date} {time_in}:00" if time_in else None
            time_out_full = f"{scan_date} {time_out}:00" if time_out else None
            if time_in_full and time_out_full:
                from app.utils.payroll import compute_hours_worked
                hours = compute_hours_worked(time_in_full, time_out_full)

            scan_type = 'time_out' if time_out_full else 'time_in'
            cur = conn.execute("""
                INSERT INTO attendance
                    (staff_id, scan_date, time_in, time_out, scan_type,
                     device_reference, notes, status, hours_worked)
                VALUES (?, ?, ?, ?, ?, 'manual-admin-entry', ?, 'present', ?)
            """, (staff_id, scan_date, time_in_full, time_out_full, scan_type,
                  notes or 'Manually entered by administrator', hours))
            attendance_id = cur.lastrowid

            import json
            conn.execute(
                "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
                ('manual_attendance_added', json.dumps({
                    'attendance_id': attendance_id, 'staff_id': staff_id,
                    'staff_name': f"{staff['first_name']} {staff['last_name']}",
                    'scan_date': scan_date, 'time_in': time_in_full, 'time_out': time_out_full,
                    'notes': notes,
                }), session['user_id'])
            )

        flash(f"Manual attendance entry recorded for {staff['first_name']} {staff['last_name']}.", 'success')
        return redirect(url_for('admin.attendance_list'))

    return render_template('admin/attendance_manual.html',
                           all_staff=[dict(r) for r in all_staff],
                           today=date.today().isoformat())


@admin_bp.route('/attendance/<int:attendance_id>/delete', methods=['POST'])
@admin_required
def attendance_delete(attendance_id):
    """Remove an attendance record (e.g. a mistaken manual entry), logging it to the audit trail first."""
    with get_db() as conn:
        record = conn.execute("""
            SELECT a.*, s.first_name || ' ' || s.last_name AS staff_name
            FROM attendance a JOIN staff s ON s.id = a.staff_id WHERE a.id=?
        """, (attendance_id,)).fetchone()
        if not record:
            flash('Attendance record not found.', 'danger')
            return redirect(url_for('admin.attendance_list'))

        import json
        conn.execute(
            "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
            ('attendance_deleted', json.dumps({k: record[k] for k in record.keys()},
                                              default=str), session['user_id'])
        )
        conn.execute("DELETE FROM attendance WHERE id=?", (attendance_id,))

    flash(f"Attendance record for {record['staff_name']} on {record['scan_date']} removed.", 'warning')
    return redirect(url_for('admin.attendance_list'))


# ─────────────────────────────────────────────
#  Payroll Computation
# ─────────────────────────────────────────────
@admin_bp.route('/payroll')
@admin_required
def payroll_list():
    with get_db() as conn:
        records = conn.execute("""
            SELECT p.*, s.first_name || ' ' || s.last_name AS staff_name, s.position,
                   ps.id AS payslip_id, ps.is_released
            FROM payroll p
            JOIN staff s ON s.id = p.staff_id
            LEFT JOIN payslip ps ON ps.payroll_id = p.id
            ORDER BY p.created_at DESC
        """).fetchall()
    return render_template('admin/payroll_list.html',
                           records=[dict(r) for r in records])


@admin_bp.route('/payroll/<int:payroll_id>/delete', methods=['POST'])
@admin_required
def payroll_delete(payroll_id):
    """
    Remove a payroll record entirely (e.g. computed by mistake). Also
    removes any associated payslip row. The full record is snapshotted
    into the audit log first so it remains inspectable after deletion.
    """
    with get_db() as conn:
        payroll = conn.execute("""
            SELECT p.*, s.first_name || ' ' || s.last_name AS staff_name
            FROM payroll p JOIN staff s ON s.id = p.staff_id WHERE p.id=?
        """, (payroll_id,)).fetchone()
        if not payroll:
            flash('Payroll record not found.', 'danger')
            return redirect(url_for('admin.payroll_list'))

        import json
        conn.execute(
            "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
            ('payroll_deleted', json.dumps({k: payroll[k] for k in payroll.keys()},
                                           default=str), session['user_id'])
        )
        conn.execute("DELETE FROM payslip WHERE payroll_id=?", (payroll_id,))
        conn.execute("DELETE FROM payroll WHERE id=?", (payroll_id,))

    flash(f"Payroll record for {payroll['staff_name']} "
          f"({payroll['pay_period_start']} – {payroll['pay_period_end']}) removed.", 'warning')
    return redirect(url_for('admin.payroll_list'))


@admin_bp.route('/payroll/compute', methods=['GET', 'POST'])
@admin_required
def payroll_compute():
    """Compute payroll for one or all staff for a given period."""
    with get_db() as conn:
        all_staff = conn.execute("""
            SELECT s.id, s.first_name || ' ' || s.last_name AS name, s.position
            FROM staff s WHERE s.employment_status='active' ORDER BY s.last_name
        """).fetchall()

    preview = None
    form_data = {}

    if request.method == 'POST':
        action = request.form.get('action', 'preview')
        staff_id     = request.form.get('staff_id', '')
        period_start = request.form.get('period_start', '')
        period_end   = request.form.get('period_end', '')
        allowances   = float(request.form.get('allowances', 0) or 0)
        allow_note   = request.form.get('allowances_note', '')
        other_ded    = float(request.form.get('other_deductions', 0) or 0)
        other_note   = request.form.get('other_deductions_note', '')
        form_data = request.form.to_dict()

        if not all([staff_id, period_start, period_end]):
            flash('Staff member and pay period dates are required.', 'danger')
        else:
            try:
                result = compute_payroll(
                    int(staff_id), period_start, period_end,
                    allowances, allow_note, other_ded, other_note
                )
                if action == 'save':
                    payroll_id = save_payroll(result, session['user_id'])
                    flash(f"Payroll saved (ID #{payroll_id}).  "
                          "You can now approve and generate a payslip.", 'success')
                    return redirect(url_for('admin.payroll_detail', payroll_id=payroll_id))
                else:
                    preview = result
            except Exception as e:
                flash(f"Computation error: {e}", 'danger')

    return render_template('admin/payroll_compute.html',
                           all_staff=[dict(r) for r in all_staff],
                           preview=preview,
                           form_data=form_data)


@admin_bp.route('/payroll/<int:payroll_id>')
@admin_required
def payroll_detail(payroll_id):
    with get_db() as conn:
        payroll = conn.execute("""
            SELECT p.*, s.first_name || ' ' || s.last_name AS staff_name,
                   s.position, s.employment_type,
                   s.daily_rate, s.monthly_rate,
                   s.sss_monthly_total, s.philhealth_monthly_total, s.pagibig_monthly_total,
                   ps.id AS payslip_id, ps.is_released
            FROM payroll p
            JOIN staff s ON s.id = p.staff_id
            LEFT JOIN payslip ps ON ps.payroll_id = p.id
            WHERE p.id = ?
        """, (payroll_id,)).fetchone()
    if not payroll:
        flash('Payroll record not found.', 'danger')
        return redirect(url_for('admin.payroll_list'))

    return render_template('admin/payroll_detail.html', payroll=dict(payroll))


@admin_bp.route('/payroll/<int:payroll_id>/approve', methods=['POST'])
@admin_required
def payroll_approve(payroll_id):
    with get_db() as conn:
        conn.execute("""
            UPDATE payroll SET status='approved', approved_by=?, approved_at=CURRENT_TIMESTAMP,
                updated_at=CURRENT_TIMESTAMP
            WHERE id=? AND status='draft'
        """, (session['user_id'], payroll_id))
        conn.execute(
            "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
            ('payroll_approved', json.dumps({'payroll_id': payroll_id}), session['user_id'])
        )
    flash('Payroll approved.', 'success')
    return redirect(url_for('admin.payroll_detail', payroll_id=payroll_id))


# ─────────────────────────────────────────────
#  Payslip Generation
# ─────────────────────────────────────────────
@admin_bp.route('/payroll/<int:payroll_id>/payslip/generate', methods=['POST'])
@admin_required
def payslip_generate(payroll_id):
    """Generate and release a payslip for an approved payroll record."""
    with get_db() as conn:
        payroll = conn.execute(
            "SELECT * FROM payroll WHERE id=?", (payroll_id,)).fetchone()
        if not payroll:
            flash('Payroll record not found.', 'danger')
            return redirect(url_for('admin.payroll_list'))
        if payroll['status'] not in ('approved', 'released'):
            flash('Payroll must be approved before generating a payslip.', 'warning')
            return redirect(url_for('admin.payroll_detail', payroll_id=payroll_id))

        # Create or update payslip record
        existing = conn.execute(
            "SELECT id FROM payslip WHERE payroll_id=?", (payroll_id,)).fetchone()
        if not existing:
            conn.execute("""
                INSERT INTO payslip (payroll_id, generated_by, is_released, released_at)
                VALUES (?, ?, 1, CURRENT_TIMESTAMP)
            """, (payroll_id, session['user_id']))
        else:
            conn.execute(
                "UPDATE payslip SET is_released=1, released_at=CURRENT_TIMESTAMP WHERE payroll_id=?",
                (payroll_id,))
        conn.execute(
            "UPDATE payroll SET status='released', updated_at=CURRENT_TIMESTAMP WHERE id=?",
            (payroll_id,))
        conn.execute(
            "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
            ('payslip_generated',
             json.dumps({'payroll_id': payroll_id}), session['user_id'])
        )
    flash('Payslip generated and released to staff member.', 'success')
    return redirect(url_for('admin.payroll_detail', payroll_id=payroll_id))


@admin_bp.route('/payroll/<int:payroll_id>/payslip/pdf')
@admin_required
def payslip_pdf(payroll_id):
    """Stream PDF payslip for download."""
    with get_db() as conn:
        payroll = conn.execute("SELECT * FROM payroll WHERE id=?", (payroll_id,)).fetchone()
        if not payroll:
            flash('Payroll not found.', 'danger')
            return redirect(url_for('admin.payroll_list'))
        staff = conn.execute("SELECT * FROM staff WHERE id=?", (payroll['staff_id'],)).fetchone()
    if not staff:
        flash('Staff not found.', 'danger')
        return redirect(url_for('admin.payroll_list'))

    pdf_bytes = generate_payslip_pdf(dict(payroll), dict(staff))
    fname = f"payslip_{staff['last_name']}_{payroll['pay_period_start']}.pdf"
    return send_file(io.BytesIO(pdf_bytes), mimetype='application/pdf',
                     as_attachment=True, download_name=fname)


# ─────────────────────────────────────────────
#  Reports
# ─────────────────────────────────────────────
@admin_bp.route('/reports')
@admin_required
def reports():
    with get_db() as conn:
        audit_log = conn.execute("""
            SELECT r.*, u.username AS generated_by_name
            FROM report r LEFT JOIN users u ON u.id = r.generated_by
            ORDER BY r.generated_at DESC LIMIT 50
        """).fetchall()
    return render_template('admin/reports.html',
                           audit_log=[dict(r) for r in audit_log])


@admin_bp.route('/reports/attendance')
@admin_required
def report_attendance():
    date_from = request.args.get('date_from',
                                  (date.today() - timedelta(days=30)).isoformat())
    date_to   = request.args.get('date_to', date.today().isoformat())
    staff_id  = request.args.get('staff_id', '')

    with get_db() as conn:
        query = """
            SELECT a.*, s.first_name || ' ' || s.last_name AS staff_name,
                   s.position
            FROM attendance a JOIN staff s ON s.id = a.staff_id
            WHERE a.scan_date BETWEEN ? AND ? AND a.scan_type='time_out'
        """
        params = [date_from, date_to]
        if staff_id:
            query += " AND a.staff_id=?"
            params.append(staff_id)
        query += " ORDER BY a.scan_date DESC, staff_name"
        records = conn.execute(query, params).fetchall()
        all_staff = conn.execute(
            "SELECT id, first_name || ' ' || last_name AS name FROM staff ORDER BY last_name"
        ).fetchall()
        # Log report generation
        conn.execute(
            "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
            ('attendance_summary',
             json.dumps({'date_from': date_from, 'date_to': date_to, 'staff_id': staff_id}),
             session['user_id'])
        )

    return render_template('admin/report_attendance.html',
                           records=[dict(r) for r in records],
                           all_staff=[dict(r) for r in all_staff],
                           date_from=date_from, date_to=date_to,
                           filter_staff=staff_id)


@admin_bp.route('/reports/payroll')
@admin_required
def report_payroll():
    date_from = request.args.get('date_from',
                                  (date.today() - timedelta(days=60)).isoformat())
    date_to   = request.args.get('date_to', date.today().isoformat())
    with get_db() as conn:
        records = conn.execute("""
            SELECT p.*, s.first_name || ' ' || s.last_name AS staff_name,
                   s.position, ps.is_released
            FROM payroll p JOIN staff s ON s.id = p.staff_id
            LEFT JOIN payslip ps ON ps.payroll_id = p.id
            WHERE p.pay_period_start >= ? AND p.pay_period_end <= ?
            ORDER BY p.pay_period_start DESC
        """, (date_from, date_to)).fetchall()
        conn.execute(
            "INSERT INTO report (report_type, parameters, generated_by) VALUES (?,?,?)",
            ('payroll_report',
             json.dumps({'date_from': date_from, 'date_to': date_to}),
             session['user_id'])
        )
    total_gross = sum(r['gross_pay'] for r in records)
    total_net   = sum(r['net_pay'] for r in records)
    return render_template('admin/report_payroll.html',
                           records=[dict(r) for r in records],
                           date_from=date_from, date_to=date_to,
                           total_gross=total_gross, total_net=total_net)
